
<br>

### Submited To: 
**Name:** Prof. Dr. Md Samsuzzaman <br>
**Department of Computer and Communication Engineering,** <br>
**Faculty of Computer Science and Engineering** <br>

<br>

### Submited By: 
**Name** : Yasin Arafat <br>
**ID:** 2102030 <br>
**Registration NO:** 10157 <br>
**Date of submission:** 1 Aug, 2025 <br>


In [7]:

import numpy as np 

def gauss_elimination(coefficient_matrix,y_matrix):
    if coefficient_matrix.shape[0] != coefficient_matrix.shape[1]:
        print("-coefficient-matrix-need-to-be-square-")
        return 
    
    if y_matrix.shape[1]>1 or y_matrix.shape[0] != y_matrix.shape[0]:
        print("-constant-vector-incorrect-")
        return
    
    
    # necessary variables:
    n = len(y_matrix)
    m = n - 1
    i = 0
    j = i -1 
    x = np.zeros(n)
    
    # create our augmentated matrix:
    augmented_matrix = np.concatenate((coefficient_matrix,y_matrix),axis=1)
    
    # applying Gauss Elimination:
    while i<n:
        if augmented_matrix[i][i] == 0:
            print("Dividing by zero error")
            return 
        # formula: R2 - R1 (R2_1,0/R1_00):
        # visulization from 2nd video:
        for j in range(i+1,n):
            scaling_factor = augmented_matrix[j][i] / augmented_matrix[i][i]
            augmented_matrix[j] = augmented_matrix[j] - (scaling_factor * augmented_matrix[i])
            print(f"{augmented_matrix} \n ")
        i = i + 1 
        
    # backward subtituion:
    # like we calcualte y value from Echelon matrix from:
    # last row
    x[m] = augmented_matrix[m][n] / augmented_matrix[m][m]
    
    for k in range(n-2,-1,-1):
        #second last row:
        x[k] = augmented_matrix[k][n]
        # column:
        for j in range(k+1,n):
            x[k] = x[k] / augmented_matrix[k][k]
            
    print(f"solution: {x}")
            
        
    
co_efficient_matrix = np.array([[1,1,3],[0,1,3],[-1,3,0]])
y_matrix = np.array([[1],[3],[5]])

gauss_elimination(co_efficient_matrix,y_matrix)



[[ 1  1  3  1]
 [ 0  1  3  3]
 [-1  3  0  5]] 
 
[[1 1 3 1]
 [0 1 3 3]
 [0 4 3 6]] 
 
[[ 1  1  3  1]
 [ 0  1  3  3]
 [ 0  0 -9 -6]] 
 
solution: [1.         3.         0.66666667]
