In [141]:


#%pip install numpy scipy 


In [142]:

import numpy as np 
from scipy.linalg import lu 

# feature data: 
obj = [[3,5,2],[1,2,0],[1,0,2]]
X = np.array(object=obj,dtype=np.float32)
X, X.shape

(array([[3., 5., 2.],
        [1., 2., 0.],
        [1., 0., 2.]], dtype=float32),
 (3, 3))

In [143]:

# target value: 
y = np.array([4,5,3],dtype=np.float32)
y

array([4., 5., 3.], dtype=float32)

In [144]:

# calcuate, X^T.X 
xtx = np.dot(a=X.transpose(),b=X)
xtx

array([[11., 17.,  8.],
       [17., 29., 10.],
       [ 8., 10.,  8.]], dtype=float32)

In [145]:

# calcuate X^T,y
xty = np.dot(a=X.transpose(),b=y)
xty

array([20., 30., 14.], dtype=float32)

In [146]:

# perform LU Decomposition 
_ , L , U = lu(xtx)

print(f"Lower triangular metrix:\n{L} \n\n")
print(f"Upper triangualr matrix:\n {U}")


Lower triangular metrix:
[[1.         0.         0.        ]
 [0.47058824 1.         0.        ]
 [0.64705884 0.48387098 1.        ]] 


Upper triangualr matrix:
 [[17.         29.         10.        ]
 [ 0.         -3.6470585   3.2941175 ]
 [ 0.          0.         -0.06451607]]


In [147]:

# Lz = xty (do: Forward Substituion)
z = np.linalg.solve(L,xty)
z

array([20.      , 20.588236, -8.903227], dtype=float32)

In [148]:
""" 
Or, with inverse, we got same result:
"""
np.dot(np.linalg.inv(L),xty)


array([20.      , 20.588234, -8.903227], dtype=float32)

In [149]:

# backword subtituion:
beta = np.linalg.solve(U,z)
beta

array([-283.00034,  119.00014,  138.00015], dtype=float32)