<br>
<br>

# `# SVD: Single value Decomposition`

<br>
<br>

In [1]:
import numpy as np 
from scipy.linalg import svd

matrix = np.array([[3,1,1],[-1,3,1]])
matrix

array([[ 3,  1,  1],
       [-1,  3,  1]])

In [2]:

U,S,V = svd(matrix)

In [3]:
U,S,V

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([3.46410162, 3.16227766]),
 array([[-4.08248290e-01, -8.16496581e-01, -4.08248290e-01],
        [-8.94427191e-01,  4.47213595e-01,  5.26260748e-16],
        [-1.82574186e-01, -3.65148372e-01,  9.12870929e-01]]))

In [4]:

# with numpy: 
u,s,v = np.linalg.svd(matrix)
u,s,v

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([3.46410162, 3.16227766]),
 array([[-4.08248290e-01, -8.16496581e-01, -4.08248290e-01],
        [-8.94427191e-01,  4.47213595e-01,  5.26260748e-16],
        [-1.82574186e-01, -3.65148372e-01,  9.12870929e-01]]))

In [12]:


# full matries = False: 
u,s,v = np.linalg.svd(matrix,full_matrices=False)
u,s,v

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([3.46410162, 3.16227766]),
 array([[-4.08248290e-01, -8.16496581e-01, -4.08248290e-01],
        [-8.94427191e-01,  4.47213595e-01,  5.26260748e-16]]))

<br>
<br>

# `#manually solve find the SVD:`

<br>
<br>

In [5]:

# step:01
# u = A . A^T 
# find eigen_matrix
u = matrix @ matrix.transpose()
eigen_values,eigen_matrix1 = np.linalg.eig(u)
eigen_values, eigen_matrix1


(array([12., 10.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [6]:

# step:01
# u = A^T . A 
# find eigen_matrix
v = matrix.T @ matrix
eigen_values , eigen_matrix2 = np.linalg.eig(v)
eigen_values,eigen_matrix2

(array([ 0., 10., 12.]),
 array([[ 1.82574186e-01, -8.94427191e-01, -4.08248290e-01],
        [ 3.65148372e-01,  4.47213595e-01, -8.16496581e-01],
        [-9.12870929e-01,  5.07704275e-16, -4.08248290e-01]]))

In [7]:
eigen_matrix2.T

array([[ 1.82574186e-01,  3.65148372e-01, -9.12870929e-01],
       [-8.94427191e-01,  4.47213595e-01,  5.07704275e-16],
       [-4.08248290e-01, -8.16496581e-01, -4.08248290e-01]])

In [14]:

# diagonal matrix: 
print(f"Orginal matrix:\n {matrix}")
print(f"Diagonal matrix: {np.diag(matrix)}")


Orginal matrix:
 [[ 3  1  1]
 [-1  3  1]]
Diagonal matrix: [3 3]


In [15]:

# Find rank of an metrix: 
print(f"rank of matrix: {np.linalg.matrix_rank(matrix)}")

rank of matrix: 2
