In [1]:


import numpy as np 
import pandas as pd 

from sklearn.feature_extraction.text import CountVectorizer


In [2]:

dataset =  {'text':['People Love To Watch Television',
    'Television is Not Good For People',
    'Lazy People Thinks Television Is Good'], 
    'output':[1,0,1]}
    

df = pd.DataFrame(data=dataset)
df

text  output
0        People Love To Watch Television       1
1      Television is Not Good For People       0
2  Lazy People Thinks Television Is Good       1

In [3]:

cv = CountVectorizer()
bow = cv.fit_transform(df["text"])

cv.vocabulary_


{'people': 6,
 'love': 4,
 'to': 9,
 'watch': 10,
 'television': 7,
 'is': 2,
 'not': 5,
 'good': 1,
 'for': 0,
 'lazy': 3,
 'thinks': 8}

In [4]:

# people: 
bow[0].toarray()


array([[0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1]])

In [5]:


# bigram:
cv3 = CountVectorizer(ngram_range=(2,2)) 
bow = cv3.fit_transform(df['text'])
print(df['text'][0])
print(cv3.vocabulary_)
bow[0].toarray()



People Love To Watch Television
{'people love': 7, 'love to': 5, 'to watch': 11, 'watch television': 12, 'television is': 9, 'is not': 3, 'not good': 6, 'good for': 1, 'for people': 0, 'lazy people': 4, 'people thinks': 8, 'thinks television': 10, 'is good': 2}


array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1]])

In [6]:


# unigram+bigram
cv3 = CountVectorizer(ngram_range=(1,2))
bow = cv3.fit_transform(df['text'])
print(df['text'][0])
print(cv3.vocabulary_)
bow[0].toarray()



People Love To Watch Television
{'people': 13, 'love': 9, 'to': 20, 'watch': 22, 'television': 16, 'people love': 14, 'love to': 10, 'to watch': 21, 'watch television': 23, 'is': 4, 'not': 11, 'good': 2, 'for': 0, 'television is': 17, 'is not': 6, 'not good': 12, 'good for': 3, 'for people': 1, 'lazy': 7, 'thinks': 18, 'lazy people': 8, 'people thinks': 15, 'thinks television': 19, 'is good': 5}


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 1]])